### ISSUE TITLE
Panic on Player::new()

### ISSUE THREAD

**Issue by fschutt** [pcwalton/rust-media#41]
Reproducing steps:

```
youtube-dl -k -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4' https://www.youtube.com/watch?v=5QyBGvZ0pHM&list=PL7odT97B5pLa-D40qMJNaLP4jvZ-HeDLO&index=19

RUST_BACKTRACE=1 ./example "Caravan Palace - Lay Down-5QyBGvZ0pHM.mp4" video/mp4
```

Result:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', libcore/result.rs:916:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:381
   3: std::panicking::default_hook
             at libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:522
   7: rust_begin_unwind
             at libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: rust_media::playback::Player::new
             at /checkout/src/libcore/result.rs:782
             at /home/felix/Development/rust-media/playback.rs:326
             at /home/felix/Development/rust-media/playback.rs:62
  11: example::main
             at /home/felix/Development/rust-media/example/example.rs:302
  12: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:480
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  15: std::rt::lang_start_internal
             at libstd/panicking.rs:459
             at libstd/panic.rs:365
             at libstd/rt.rs:58
  16: main
  17: __libc_start_main
  18: _start
```

rustc:

```
rustc 1.25.0-nightly (61452e506 2018-01-09)
binary: rustc
commit-hash: 61452e506f0c88861cccaeea4ced3419bdb3cbe0
commit-date: 2018-01-09
host: x86_64-unknown-linux-gnu
release: 1.25.0-nightly
LLVM version: 4.0
```

yasm:

```
yasm 1.3.0
Compiled on May  3 2015.
Copyright (c) 2001-2014 Peter Johnson and other Yasm developers.
Run yasm --license for licensing overview and summary.
```

libvpx-dev:

```
Source: libvpx
Version: 1.6.1-3
Depends: libvpx4 (= 1.6.1-3)
Description: VP8 and VP9 video codec (development files)
 VP8 and VP9 are open video codecs, originally developed by On2 and released
 as open source by Google Inc. They are the successor of the VP3 codec,
 on which the Theora codec was based.
 .
 This package contains the development libraries, header files needed by
 programs that want to compile with libvpx.
```

**Comment by fschutt** [comment]
Just wanted to add, the default video "Never gonna give you up" from the README is blocked in some countries. You might want to fix that.

**Comment by meggrasse** [comment]
Not sure if relevant anymore, but I solved this by using https://github.com/christoph-heiss/rust-media
